### ISSUE TITLE
Gap detection and handling

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#90]
Say a node is responsible for a stream. If it has received messages with offsets 1, 2, 3, 4, 5, and then receives a message with offset 10, it is apparent that some messages are still on their way or have been lost. Before processing message number 10, it should probably wait (and/or request?) for the missing messages before proceeding. This ensures that all messages are processed and in order.

**Comment by hpihkala** [comment]
Will nodes "process" messages in some way? Should the nodes care about gaps or order?

Currently, the gapfill protocol is on the _client_ (as the client is the one who processes messages and can have an opinion about whether gaps and ordering matter or not). It works like this:

- All messages carry a number (called _offset_ due to Kafka naming)
- All messages also optionally carry the number of the previous message in that stream (_previousOffset_)
- The offsets don't need to be sequential (1,2,3) but must be strictly increasing (1, 36, 89)
- The client keeps in memory the latest successfully received message number

In your example, the client works like this (implemented in the JS client):

- First message: offset 1, previousOffset null => accept. `lastProcessedOffset = 1`
- Second message: offset 2, previousOffset 1. Because `previousOffset != null && previousOffset == lastProcessedOffset` => accept.
- ... similarly up to message 5
- offset 10, previousOffset: 9 (say)=> buffer message 10 and query for messages with offsets between `lastProcessedOffset+1` and `previousOffset (9)`. When these are successfully received and processed, continue from message 10.

**Comment by harbu** [comment]
I guess the simple approach would be to leave it as it is. Thus clients are responsible for gap handling, and clients can query for missing messages. That does making implementing clients harder. On the other hand, as you said, it affords clients the flexibility to handle gaps as they see fit.

By the way. Since we don't have to work with a single Kafka topic anymore, I guess we can have sequential numbering? Can't say for certain if we need that assumption anywhere. I guess being able to count the number of missing messages is a cool  "decentralized" property, but then again, the leader of a stream already is able to tell how many messages are in between.

**Comment by hpihkala** [comment]
> That does making implementing clients harder.

It does, but gapfill isn't super complicated, and it's already implemented in the JS client. I'd continue with the current `simple server, complex client` vs. `complex server, simple client` for now. Creating the network is hard enough - perhaps later we'll recognize opportunities to move some of the complexity from the client to the node.

One of the problems with the `complex server, simple client` approach would be the need to track which clients have received which messages. It's certainly a burden, and still, ultimately only the client can know the truth.

> By the way. Since we don't have to work with a single Kafka topic anymore, I guess we can have sequential numbering? Can't say for certain if we need that assumption anywhere. I guess being able to count the number of missing messages is a cool "decentralized" property, but then again, the leader of a stream already is able to tell how many messages are in between.

Maybe indeed! But I wouldn't rely on that assumption just yet, since we don't really yet know whether we'll do stream-level or partition-level leaders and numbering. If we do partition-level, then the numbering won't be sequential for a given stream (just like today with Kafka).
